options:
  # Tự động cập nhật （bạn nên bật cái này）
  auto-update: true

  # Có bật hỗ trợ PlaceholderAPI hay không (có thể lấy trạng thái bật HUD của người chơi)
  placeholder-api-support: true

  # Có bật sử dụng SlimefunTranslation để hiển thị tên vật phẩm đã dịch hay không
  slimefun-translation-support: true

waila:

  # Khi đặt true, sẽ tắt toàn bộ tính năng.
  # Ưu tiên cao nhất, bỏ qua thiết lập 'disabled-in' và tùy chọn của người chơi.
  disabled: false

  # Thiết lập những thế giới cần tắt WAILA.
  disabled-in: []

  # Vị trí hiển thị, có thể là 'bossbar' hoặc 'hotbar'.
  location: bossbar

  # Có sử dụng màu tên gốc của khối hay không. Khi tắt, sẽ dùng màu trắng.
  use-original-colors: true

  # Màu thanh máu Boss, phải viết theo kiểu 'snake_case'.
  # 'inherit' nghĩa là khớp với màu gần nhất 'match the color of the bossbar to that of the text'.
  # 'default' là màu trắng
  bossbar-color: inherit

  # Bộ quản lý/kết nối hàng hóa có hiển thị kích thước mạng vận chuyển hay không
  show-cargo-size: true

  # Nút nhập/xuất hàng hóa có hiển thị kênh hay không
  show-cargo-channel: true

  # Bộ quản lý/kết nối năng lượng có hiển thị kích thước mạng năng lượng hay không
  show-energy-size: true

  # Tụ điện có hiển thị lượng điện đã lưu trữ hay không
  show-energy-stored: true

  # Có hiển thị tiến độ máy hay không (hỗ trợ hầu hết các máy)
  show-machine-progress: true

  # Có hiển thị hiệu suất máy phát điện hay không (hỗ trợ hầu hết máy phát điện)
  show-generator-generation: true

  # Khoảng thời gian cập nhật WAILA, tính bằng tick MC
  tick-rate: 10