name: Bug Report
description: Báo cáo Bug hoặc sự cố của plugin này
labels: ["bug"]
assignees:
  - ybw0014
body:
  - type: markdown
    attributes:
      value: |
        ## Chào mừng bạn đến với hệ thống theo dõi vấn đề của SlimefunGuguProject
        Bạn đang báo cáo Bug xuất hiện ở phiên bản Việt hóa/Hán hóa của SlimeHUD.
        Mọi ý kiến, góp ý xin vui lòng gửi đến [Nhóm QQ](https://ybw0014.net/go/sf-qgroup) để phản hồi.
        Khuyến nghị đọc [bài viết này](https://slimefun-wiki.guizhanss.cn/How-to-report-bugs) trước để hiểu cách báo cáo Bug đúng cách.

        <strong><i>Bạn phải điền vào các mục biểu mẫu được đánh dấu sao (*)</i></strong>

  - type: checkboxes
    id: checklist
    attributes:
      label: Các mục cần kiểm tra
      description: Trước khi báo cáo, bạn cần xác nhận
      options:
        - label: Bạn đang sử dụng phiên bản được tải xuống từ trang build
          required: true
        - label: Bạn đã kiểm tra checksum của file đã tải xuống, xác nhận file đã được tải xuống đầy đủ
          required: false
        - label: Bạn chưa thực hiện bất kỳ thay đổi nào đối với nội dung file đã tải xuống
          required: true
        - label: Bạn đã tìm kiếm trong [danh sách các vấn đề đã biết](https://github.com/SlimefunGuguProject/SlimeHUD/issues) và không tìm thấy vấn đề tương tự
          required: true

  - type: textarea
    id: description
    attributes:
      label: Mô tả vấn đề
      description: |
        Mô tả chi tiết vấn đề mà bạn muốn báo cáo
        Cung cấp thông tin chi tiết sẽ giúp chúng tôi xử lý vấn đề nhanh hơn
      placeholder: Chỉ nói "không dùng được" thì nhà phát triển không thể xác định được vấn đề.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Các bước tái hiện
      description: |
        Vui lòng mô tả chi tiết cách để tái hiện lại vấn đề này
        Nếu có video, vui lòng cung cấp liên kết video tại đây
      placeholder: |
        1. xxx
        2. xxx
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Hành vi mong đợi
      description: |
        Bạn nghĩ điều gì lẽ ra nên xảy ra
        Đôi khi, nguyên nhân của vấn đề là do bạn hiểu sai về một tính năng nào đó.
    validations:
      required: true

  - type: input
    id: server-log
    attributes:
      label: Nhật ký máy chủ
      description: |
        Vui lòng kiểm tra xem nhật ký máy chủ có chứa bất kỳ lỗi nào không, nếu có vui lòng tải lên [https://paste.guizhanss.net/](https://paste.guizhanss.net/) và điền liên kết vào đây.
        **Không dán trực tiếp nhật ký vào đây**
      placeholder: https://paste.guizhanss.net/...
    validations:
      required: false

  - type: input
    id: error-report
    attributes:
      label: Báo cáo lỗi
      description: |
        Nếu nhật ký máy chủ có đề cập đến file trong `/plugins/Slimefun/error-reports` (tức báo cáo lỗi)
        vui lòng tải lên [https://paste.guizhanss.net/](https://paste.guizhanss.net/) và điền liên kết vào đây.
        **Không dán trực tiếp báo cáo lỗi vào đây**
      placeholder: https://paste.guizhanss.net/...
    validations:
      required: false

  - type: dropdown
    id: server-software
    attributes:
      label: Phần mềm máy chủ
      description: Vui lòng chọn phần mềm máy chủ mà bạn đang sử dụng
      options:
        - Spigot
        - Paper
        - Purpur
        - Airplane
        - Khác (vui lòng ghi rõ trong mô tả vấn đề)
    validations:
      required: true

  - type: input
    id: minecraft-version
    attributes:
      label: Phiên bản Minecraft
      description: Vui lòng điền phiên bản Minecraft của bạn
    validations:
      required: true

  - type: textarea
    id: slimefun-version
    attributes:
      label: Phiên bản Slimefun
      description: |
        Vui lòng điền phiên bản Slimefun
        (ví dụ v4.9-canary-08120db)
        Nếu bạn có quyền quản trị viên, khuyến nghị chạy lệnh `/sf versions`, chụp màn hình và tải lên **toàn bộ nội dung** đầu ra của lệnh tại đây.
    validations:
      required: true

  - type: input
    id: version-plugin
    attributes:
      label: Phiên bản plugin
      description: |
        Vui lòng điền phiên bản plugin
        (ví dụ Build 1 (git x114514))
    validations:
      required: true
      