blank_issues_enabled: false
contact_links:
  - name: Không có tài khoản Github? Không biết cách sử dụng Github?
    url: https://ybw0014.net/go/sf-qgroup
    about: Nhấn vào nút bên phải để tham gia nhóm QQ và phản hồi